# Generated by Django 4.2.10 on 2025-06-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NBA", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
    ]
