# Generated by Django 4.2.10 on 2025-06-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NBA", "0002_comment_is_pinned"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="venue",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="away_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="home_score",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
